version: "2"

services:

  app:
    
    build: ./henry_app

    links:
      - db

    ports:
      - "5002:5000"

    volumes:
      - ./henry_app/:/henry_app/

  db:
    image: mysql:5.7
    
    ports:
      - "32002:3306"
    
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro